\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{graphics}
\usepackage{booktabs}
\usepackage{colortbl, xcolor}
\begin{document}

<<echo = FALSE,message=FALSE,results='asis'>>=
library(xtable)
options(xtable.caption.placement = "top")

rws_cv <- c(-1, seq(1, 6, by = 2))
colour_cv <- c("\\rowcolor{white!100}", rep("\\rowcolor[gray]{0.85}", length(rws_cv) - 1))

tab <- head(iris)


sth <- capture.output(print(xtable(tab, caption = "Table for Konstantin.", align = c(rep("c", 5), "l")), 
      include.rownames = FALSE))

row_11 <- strsplit(sth[11], " & ")[[1]]
row_11[2] <- paste0("\\textbf{", row_11[2], "}")
row_11 <- paste(row_11, collapse = " & ")
sth[11] <- row_11

for (i in sth)
  cat(i, "\n")


@



\end{document}